# Generated by Django 4.2.3 on 2023-07-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="airplanetype",
            name="name",
        ),
        migrations.AddField(
            model_name="airplanetype",
            name="brand",
            field=models.CharField(default=2, max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="airplanetype",
            name="model",
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
