# Generated by Django 4.2.3 on 2023-07-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0003_remove_airplanetype_name_airplanetype_brand_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplanetype",
            name="default_row",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="airplanetype",
            name="default_seats_in_row",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
