# Generated by Django 4.2.3 on 2023-07-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0005_alter_ticket_flight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
