# Generated by Django 4.2.3 on 2023-07-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0007_alter_order_options_alter_ticket_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="crew",
            field=models.ManyToManyField(
                blank=True, related_name="airplanes", to="airport.crew"
            ),
        ),
    ]
